---
- name: Add nginx apt key
  apt_key: id=7BD9BF62 url=http://nginx.org/keys/nginx_signing.key

- name: Add nginx apt repository
  apt_repository: repo='deb http://nginx.org/packages/debian/ wheezy nginx'

- name: Install nginx
  apt: pkg=nginx

- name: Create directory for the protocol-agnostic parts of the nginx enabled sites configuration
  file: path=/etc/nginx/sites-enabled-agnostic state=directory owner=www-data group=www-data mode=0770

- name: Copy the protocol-agnostic parts of the nginx enabled sites configuration
  copy: src={{item}} dest=/etc/nginx/sites-enabled-agnostic
  with_fileglob:
    - ./sites-enabled-agnostic/*
  notify: Reload nginx

- name: Copy nginx enabled sites configuration
  template: src="./sites-enabled/all.j2" dest=/etc/nginx/sites-enabled/all
  notify: Reload nginx

- name: Copy nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: Reload nginx

- name: Delete /etc/nginx/conf.d/default.conf
  file: path=/etc/nginx/conf.d/default.conf
        state=absent
  notify: Reload nginx

- name: Create directoy for favicons
  action: file path=/usr/share/nginx/favicons state=directory owner=www-data group=www-data mode=0770

- name: Copy favicons
  copy: src={{item}} dest=/usr/share/nginx/favicons owner=www-data group=www-data mode=0770
  with_fileglob:
    - ./favicons/*.ico

- name: Create directoy for error pages
  action: file path=/usr/share/nginx/errorpages state=directory owner=www-data group=www-data mode=0770

- name: Copy error pages
  copy: src={{item}} dest=/usr/share/nginx/errorpages owner=www-data group=www-data mode=0770
  with_fileglob:
    - ./errorpages/*.*

- name: Copy default robots.txt
  copy: src=robots.txt dest=/usr/share/nginx/default owner=www-data group=www-data mode=0770

- name: Copy default index.html
  copy: src=default.index.html dest=/usr/share/nginx/default/index.html owner=www-data group=www-data mode=0770

- name: Set firewall rules
  command: ufw allow {{item}}
  with_items:
    - http/tcp
    - https/tcp
  register: ufw_result
  changed_when: "'Rule added' in ufw_result.stdout"

