- name: Copy apache2 sites to sites-enabled
  copy: src={{item}} dest=/etc/apache2/sites-enabled
  with_fileglob:
    - ./sites-enabled/*
  notify: Reload apache2

- name: Copy additional apache2 configuration files
  copy: src={{item}} dest=/etc/apache2/conf-enabled
  with_fileglob:
    - ./conf-enabled/*
  notify: Reload apache2
