- name: Create user "{{item.name}}"
  user: name={{item.name}} groups={{item.groups}} shell=/bin/zsh
  with_items: users

- name: Upload {{item.name}}'s public key
  authorized_key: user={{item.name}} key="{{ lookup('file', './ssh/' ~ item.name ~ '.pub') }}"
  with_items: users

