- name: Install ansible dependencies
  raw: apt-get install -y python-apt python-simplejson

- name: Install packages
  apt: pkg={{item}}
  with_items:
    - denyhosts
    - fail2ban
    - git
    - htop
    - lsof
    - lynis
    - mosh
    - nano
    - netcat
    - python3
    - python-software-properties
    - rkhunter
    - tmux
    - vim
    - ufw
    - zip
    - zsh

# Don't edit without validating first
- name: Allow users in the sudo group to run sudo without a password
  lineinfile: dest=/etc/sudoers
              regexp='^\%sudo'
              line='%sudo ALL=(ALL) NOPASSWD:ALL'

- include: create_user.yml user={{item.name}} group={{item.group}}
  with_items:
    - { name: 'kudu', group: 'sudo' }
    - { name: 'addshore', group: 'sudo' }
    - { name: 'johnflewis', group: 'sudo' }

- name: Copy backup.sh
  template: src=backup.sh dest=/root/backup.sh

- name: Create a cronjob for backup.sh
  cron: name="backup.sh"
        user="root"
        minute=0
        hour=0
        job="/root/backup.sh > /var/log/backup.log 2>&1"

- name: Copy ansible logrotate configuration
  copy: src="./logrotate.d/ansible" dest=/etc/logrotate.d

- name: Copy quickscripts
  copy: src={{item}} dest=/root/{{item|basename}} owner=root group=root mode=770
  with_fileglob:
    - ./quickscripts/*

- name: Set firewall rules
  command: ufw allow ssh/tcp 60000:61000/udp
  register: ufw_result
  changed_when: "ufw_result.stdout.startswith('Rule')"

- name: Check status of ufw
  command: ufw status
  register: ufw_status
  changed_when: False # never report as "changed"

- name: Check config of ufw
  command: cat /etc/ufw/ufw.conf
  register: ufw_config
  changed_when: False # never report as "changed"

- name: Disable logging (workaround for known bug in Debian 7)
  command: ufw logging off
  when: "ansible_lsb['codename'] == 'wheezy' and 'LOGLEVEL=off' not in ufw_config.stdout"

- name: Enable ufw
  command: ufw --force enable
  when: "ufw_status.stdout.startswith('Status: inactive') or 'ENABLED=yes' not in ufw_config.stdout"

