- name: Copy default ufw default settings
  copy: src="./ufw/default" dest=/etc/default/ufw

- name: Copy ufw files
  copy: src=./ufw/{{item}} dest=/etc/ufw/{{item|basename}} owner=root group=root mode=700
  with_items:
    - after.rules
    - before.rules

- name: Allow access on all internal production IPs
  ufw: rule=allow src={{ item }}
  with_items:
  # prod5 intv4
  - 10.131.243.246
  # prod6 intv4
  - 10.131.232.174
  # prod7 intv4
  - 10.131.232.37
  # prod8 intv4
  - 10.131.243.245
  # prod9 intv4
  - 10.131.243.244
  # prod10 intv4
  - 10.131.243.49
  # prod11 intv4
  - 10.131.243.247
  # prod12 intv4
  - 10.131.209.107

- name: Remove old access rules
  ufw: rule=allow src={{ item }} delete=yes
  with_items:
  - 178.62.7.226
  - 178.62.7.230
  - 2a03:b0c0:1:d0::b7:a001
  - 10.131.243.243

- name: Allow ssh access
  ufw: rule=allow port=22

- name: Allow DNS port
  ufw: rule=allow port=53

- name: Enable ufw
  ufw: state=enabled policy=deny
